export default {
  form: document.querySelector('form'),
  favoriteBtn: document.querySelector('#favorites'),
  input: document.querySelector('.thumb-input__text'),
  favoriteCityList: document.querySelector('.favorite-city__list'),
  btnNext: document.querySelector('.favorite-city__btnNext'),
  btnPrev: document.querySelector('.favorite-city__btnPrev'),
  homeContainer: document.querySelector('.home-container'),
  fiveDaysNode: document.querySelector('.five-days-container'),
  btnDaysNode: document.querySelector('.home-days-btn'),
  btnContainerNode: document.querySelector('.home-buttons'),
  btnShowChartNode: document.querySelector('.show-chart__wrap'),
  ChartNode: document.querySelector('.chart'),
  btnHideChartNode: document.querySelector('.hide-chart__wrap-btn'),
};
